WIT_AI_ACCESS_TOKEN: 'YGBMYESQ37ZYBYMVPYSWWUHEOE4VWNR4'
FACEBOOK_KEY: '1370472936397600'
FACEBOOK_SECRET: 'daf3bbbeb43b1d76609ed66dbe89eb8d'
CLOUDINARY_NAME: 'geek-hub'
CLOUDINARY_API_KEY: '794917397752141'
CLOUDINARY_API_SECRET: 'OfqDME_lm-B1o0pAOTSJWmCXPLU'